"""Fun intents: jokes, riddles, quotes, surprising facts and light games."""

ROWS = [
    ("a programming joke", "Why do programmers prefer dark mode? Because light attracts bugs. 🐛", {"templ": False, "asks": ["another joke", "tell me another joke", "joke about programming", "programming joke", "make me laugh again"], "keys": ["another-joke"]}),
    ("a loop joke", "I told my computer I needed a break — it said \"no problem, I will just keep running.\" It is still going. 🔁", {"templ": False, "asks": ["joke about loops", "loop joke", "while loop joke"], "keys": ["loop-joke"]}),
    ("a database joke", "A SQL query walks into a bar, approaches two tables and asks: \"May I join you?\" 🍻", {"templ": False, "asks": ["joke about databases", "database joke", "sql joke", "join joke"], "keys": ["sql-joke"]}),
    ("a css joke", "Two CSS properties walk into a bar. One says to the other: \"Hey, why did the bar move?\" The other replies: \"I do not know, but I have a margin-top problem now.\" 📏", {"templ": False, "asks": ["css joke", "joke about css", "frontend joke"], "keys": ["css-joke"]}),
    ("an ai joke", "Why did the AI go to therapy? It had too many deep issues and unresolved layers. 🧠", {"templ": False, "asks": ["ai joke", "joke about ai", "machine learning joke", "neural network joke"], "keys": ["ai-joke"]}),
    ("a git joke", "I tried to commit my feelings, but they were already staged… and then the merge conflict made me cry in ten branches. 🌳", {"templ": False, "asks": ["git joke", "joke about git", "github joke"], "keys": ["git-joke"]}),
    ("a hardware joke", "There are only two hard things in computing: cache invalidation, naming things, and off-by-one errors. 🔧", {"templ": False, "asks": ["hardware joke", "computer joke", "tech joke"], "keys": ["hardware-joke"]}),
    ("a bug joke", "A programmer's spouse asks: \"Go to the store and buy a loaf of bread. If they have eggs, buy a dozen.\" The programmer returns with twelve loaves of bread. 🥖", {"templ": False, "asks": ["joke about bugs", "funny programming joke", "nerd joke", "geek joke"], "keys": ["bug-joke"]}),

    ("a riddle", "Riddle: I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I? — An echo. 🌫️", {"templ": False, "asks": ["riddle", "tell me a riddle", "give me a riddle", "brain teaser"], "keys": ["riddle"]}),
    ("a harder riddle", "Riddle: The more you take, the more you leave behind. What am I? — Footsteps. 👣", {"templ": False, "asks": ["harder riddle", "another riddle", "difficult riddle"], "keys": ["riddle-2"]}),
    ("a math riddle", "Riddle: What three positive numbers give the same answer when added and multiplied? — 1, 2 and 3: 1+2+3 = 6, and 1×2×3 = 6. ✖️", {"templ": False, "asks": ["math riddle", "number riddle", "riddle about numbers"], "keys": ["riddle-math"]}),

    ("a pun", "I would tell you a UDP joke, but you might not get it. 📡", {"templ": False, "asks": ["pun", "tell me a pun", "dad joke", "tell me a dad joke"], "keys": ["pun"]}),
    ("a coding pun", "Why did the function return early? It had a Promise to keep and a callback to catch. 😄", {"templ": False, "asks": ["coding pun", "programming pun", "funny pun"], "keys": ["pun-2"]}),

    ("a quote by feynman", "\"What I cannot create, I do not understand.\" — Richard Feynman's blackboard, 1988. It is also a decent argument for why Farell builds things instead of just reading about them. ✍️", {"templ": False, "asks": ["feynman quote", "quote about understanding", "quote about building"], "keys": ["feynman-quote"]}),
    ("a quote by knuth", "\"Premature optimization is the root of all evil.\" — Donald Knuth, 1974. Write it clearly first; make it fast only where measurement says it matters. ⚙️", {"templ": False, "asks": ["knuth quote", "quote about optimization", "quote about performance"], "keys": ["knuth-quote"]}),
    ("a quote about mistakes", "\"The only real mistake is the one from which we learn nothing.\" — widely attributed to Henry Ford. A useful lens for debugging, exams, and life in general. 🛠️", {"templ": False, "asks": ["quote about mistakes", "quote about failure", "motivational quote", "quote about learning"], "keys": ["mistake-quote"]}),

    ("an octopus fact", "An octopus has three hearts, blue blood, and about 500 million neurons — two-thirds of them in its arms. It can taste with its skin and squeeze through any gap bigger than its beak, which is the only hard part of its body. 🐙", {"templ": False, "asks": ["octopus fact", "facts about octopus", "tell me about octopus"], "keys": ["octopus"]}),
    ("a honey fact", "Honey does not spoil: it is low in water, acidic, and naturally produces hydrogen peroxide, so bacteria cannot grow in it. Sealed pots have been found in ancient tombs still edible — though most claims of \"3,000-year-old honey\" are hard to verify. 🍯", {"templ": False, "asks": ["honey fact", "does honey expire", "facts about honey"], "keys": ["honey"]}),
    ("a banana fact", "Botanically, a banana is a berry, a strawberry is not, and the banana plant is technically a giant herb. The banana you eat is a clone of one variety, which is why a single disease can threaten the whole crop. 🍌", {"templ": False, "asks": ["banana fact", "is a banana a berry", "facts about bananas"], "keys": ["banana"]}),
    ("an eiffel tower fact", "The Eiffel Tower grows about 15 centimeters taller in summer — the iron expands in the heat and contracts in winter. It also sways slightly in strong wind, by design. 🗼", {"templ": False, "asks": ["eiffel tower fact", "facts about the eiffel tower"], "keys": ["eiffel"]}),
    ("a blue whale fact", "A blue whale's heart is roughly the size of a small car and its tongue can weigh as much as an elephant. It is the largest animal known to have ever lived — bigger than any dinosaur. 🐋", {"templ": False, "asks": ["blue whale fact", "largest animal", "facts about whales"], "keys": ["whale"]}),
    ("a cat fact", "Cats cannot taste sweetness — a defect in their sweetness receptor gene. They also purr at frequencies that may promote healing, though the science there is suggestive rather than settled. 🐱", {"templ": False, "asks": ["cat fact", "facts about cats", "why do cats purr"], "keys": ["cats"]}),
    ("a goldfish fact", "Goldfish are not limited to three-second memories — studies show they can remember tasks for months. The myth persists because it is a fun thing to be wrong about. 🐟", {"templ": False, "asks": ["goldfish fact", "goldfish memory", "facts about goldfish"], "keys": ["goldfish"]}),
    ("a space fact", "In space you would not instantly freeze or explode — you would first run out of air. Astronauts are protected mostly from vacuum's fast effects: no pressure, no oxygen, and boiling liquids. Space is a harsh vacuum, not a freezer. 🚀", {"templ": False, "asks": ["space fact", "what happens in space", "facts about space"], "keys": ["space-fact"]}),
    ("a great wall fact", "The Great Wall of China is not visible to the naked eye from space — the claim is a myth, though it is long enough (over 21,000 km of walls) that plenty of astronauts wish it were true. 🧱", {"templ": False, "asks": ["great wall fact", "is the great wall visible from space", "facts about the great wall"], "keys": ["greatwall"]}),
    ("a chill fact", "The coldest place on Earth is Antarctica's high plateau, where temperatures have dropped below −89 °C. The coldest permanently inhabited place is Oymyakon, Russia — where residents still go to school at −50 °C. 🥶", {"templ": False, "asks": ["coldest place on earth", "fact about cold", "coldest temperature"], "keys": ["coldest"]}),

    ("would you rather", "Would you rather: code that is fast but unreadable, or slow but beautiful? I would choose... whatever Farell would test. That is the site's actual philosophy: measure, then decide. 🤔", {"templ": False, "asks": ["would you rather", "play would you rather", "ask me would you rather"], "keys": ["wyr"]}),
    ("would you rather space", "Would you rather explore the deep ocean or deep space? I am a web page, so I am partial to anywhere with Wi-Fi — but Farell has built for the ocean (Ripple's satellite data) and for space (satellites up close). 🌊🚀", {"templ": False, "asks": ["ocean or space", "deep ocean or deep space"], "keys": ["wyr-2"]}),
    ("a superpower question", "If I could pick one superpower: remembering every question ever asked. Which is suspicious — that is just a database. What superpower would you pick? 🦸", {"templ": False, "asks": ["what superpower would you want", "if you had a superpower", "superpower question"], "keys": ["superpower"]}),
    ("a fortune", "Fortune cookie mode: \"A commit a day keeps the panic away.\" 🥠", {"templ": False, "asks": ["fortune", "tell my fortune", "fortune cookie", "predict my future"], "keys": ["fortune"]}),
    ("a toast", "A toast: to finished projects, honest READMEs, and bugs that reproduce on the first try. 🥂", {"templ": False, "asks": ["give me a toast", "make a toast", "say a toast"], "keys": ["toast"]}),
    ("a limerick", "There once was a site built by hand, with a sky and a pixel-art man. It loads with no server, no model, no key — and answers your questions as fast as you can. 🌤️", {"templ": False, "asks": ["limerick", "write me a poem", "make a poem", "poem about the site"], "keys": ["poem"]}),
]
