"""Build js/wanderly-kb.js - Wanderly's extended knowledge base.

Authoring source: tools/wk_data/*.py (plain Python row tables).
Run:              python tools/build_wanderly_kb.py

Row format (per module: ROWS = [...]):
    (topic, answer)
    (topic, answer, {"plural": True, "art": "a", "asks": [...], "keys": [...],
                     "templ": False, "follow": [...], "more": "...",
                     "links": [{"t": "...", "h": "..."}], "page": {...}})

Conventions:
- templ=True (default) generates: "what is {art} {topic}" / "what are {topic}",
  "tell me about", "explain", "define" (plus any explicit `asks`).
  Use templ=False + explicit `asks` for chat-style intents.
- Never uses apostrophes in generated asks (the engine's normalize() strips them).
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from wk_data import aiml, earth, farell, fun, life, mathx, science, smalltalk, tech  # noqa: E402

ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "js", "wanderly-kb.js")

MODULES = [
    ("smalltalk", smalltalk.ROWS),
    ("science", science.ROWS),
    ("earth", earth.ROWS),
    ("math", mathx.ROWS),
    ("tech", tech.ROWS),
    ("aiml", aiml.ROWS),
    ("life", life.ROWS),
    ("farell", farell.ROWS),
    ("fun", fun.ROWS),
]

STOP = {"the", "a", "an", "of", "and", "in", "on", "to", "for", "with"}

SINGULAR_S_EXCEPTIONS = {
    "mars", "chaos", "statistics", "mathematics", "maths", "physics", "ethics",
    "politics", "economics", "gps", "dns", "https", "kubernetes", "redis",
}


def is_plural(topic, opts):
    if "plural" in opts:
        return bool(opts["plural"])
    last = topic.lower().split()[-1].strip(".,()[]'") if topic.split() else ""
    if last in SINGULAR_S_EXCEPTIONS:
        return False
    if last.endswith(("ss", "us", "is", "cs")):
        return False
    return last.endswith("s")


def keys_for(topic, extra):
    out = []
    for w in topic.lower().replace("'", "").split():
        w = w.strip(".,()[]")
        if w and w not in STOP and len(w) >= 3 and w not in out:
            out.append(w)
    for k in extra or []:
        k = k.lower().strip()
        if k and k not in out:
            out.append(k)
    return out


def asks_for(topic, opts, seen):
    out = []
    problems = []
    if opts.get("templ", True):
        art = (opts.get("art") or "").strip()
        if is_plural(topic, opts):
            head = "what are " + topic
        else:
            head = "what is " + (art + " " if art else "") + topic
        out.extend(
            [
                head,
                "tell me about " + (art + " " if art and not is_plural(topic, opts) else "") + topic,
                "explain " + (art + " " if art and not is_plural(topic, opts) else "") + topic,
                "define " + topic,
            ]
        )
    for a in opts.get("asks", []):
        a = a.strip().lower()
        if a:
            out.append(a)
    keep = []
    for a in out:
        if a in seen:
            problems.append("duplicate ask pattern: %r (topic %r, first used by %r)" % (a, topic, seen[a]))
            continue
        seen[a] = topic
        keep.append(a)
    return keep, problems


def build():
    seen = {}
    entries = []
    topics = set()
    problems = []
    for name, rows in MODULES:
        for row in rows:
            topic, answer = row[0], row[1]
            opts = row[2] if len(row) > 2 else {}
            if topic in topics:
                raise SystemExit("duplicate topic in %s: %r" % (name, topic))
            topics.add(topic)
            asks, probs = asks_for(topic, opts, seen)
            problems.extend("[%s] %s" % (name, p) for p in probs)
            entry = {
                "asks": asks,
                "keys": keys_for(topic, opts.get("keys")),
                "a": answer,
            }
            for field in ("more", "follow", "links", "page"):
                if field in opts:
                    entry[field] = opts[field]
            entries.append(entry)

    if problems:
        print("PROBLEMS (%d):" % len(problems))
        for p in problems:
            print("  " + p)
        raise SystemExit(1)

    total_asks = sum(len(e["asks"]) for e in entries)
    header = (
        "/* Wanderly extended knowledge base - GENERATED by tools/build_wanderly_kb.py.\n"
        "   Do not edit by hand; edit tools/wk_data/*.py and re-run the builder.\n"
        "   Rows: %d | ask patterns: %d */\n" % (len(entries), total_asks)
    )
    body = ",\n".join(
        json.dumps(e, ensure_ascii=False, separators=(",", ":")) for e in entries
    )
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header)
        fh.write("window.WANDERLY_KB_EXTRA = [\n")
        fh.write(body)
        fh.write("\n];\n")

    print("wrote %s" % OUT)
    print("rows: %d | ask patterns: %d" % (len(entries), total_asks))
    for name, rows in MODULES:
        print("  %-10s %d rows" % (name, len(rows)))
    return 0


if __name__ == "__main__":
    raise SystemExit(build())
